### ISSUE TITLE
Getting INTERNALERROR> KeyError:  when using --csv-columns option

### ISSUE THREAD

**Issue by vishalkoolkarni** [nicoulaj/pytest-csv#19]
When I am trying run my test with --csv along with --csv-columns option I am getting INTERNALERROR> KeyError: .It runs fine if I remove the --csv-columns option.

PS C:\Users\visha\PycharmProjects\GUI_Automation> pytest --html=Reports\report.html --self-contained-html --csv .\Logs\output.csv --csv-columns id,module,file,markers,status,duration .\Tests\test_mpr3_creation.py
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "c:\users\visha\pycharmprojects\gui_automation\venv\lib\site-packages\_pytest\main.py", line 265, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "c:\users\visha\pycharmprojects\gui_automation\venv\lib\site-packages\_pytest\config\__init__.py", line 982, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "c:\users\visha\pycharmprojects\gui_automation\venv\lib\site-packages\pluggy\_hooks.py", line 277, in call_historic
INTERNALERROR>     res = self._hookexec(self.name, self.get_hookimpls(), kwargs, False)
INTERNALERROR>   File "c:\users\visha\pycharmprojects\gui_automation\venv\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "c:\users\visha\pycharmprojects\gui_automation\venv\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "c:\users\visha\pycharmprojects\gui_automation\venv\lib\site-packages\pluggy\_result.py", line 60, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "c:\users\visha\pycharmprojects\gui_automation\venv\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "c:\users\visha\pycharmprojects\gui_automation\venv\lib\site-packages\pytest_csv\_plugin.py", line 83, in pytest_configure
INTERNALERROR>     columns = OrderedDict((column_id, columns_registry[column_id.strip()])
INTERNALERROR>   File "c:\users\visha\pycharmprojects\gui_automation\venv\lib\site-packages\pytest_csv\_plugin.py", line 83, in <genexpr>
INTERNALERROR>     columns = OrderedDict((column_id, columns_registry[column_id.strip()])
INTERNALERROR> KeyError: '.\\Tests\\test_mpr3_creation.py'
PS C:\Users\visha\PycharmProjects\GUI_Automation>

**Comment by vishalkoolkarni** [comment]
The command worked fine after moving the testscript name before --csv-columns. Perhaps -csv-columns was considering test script name as column

PS C:\Users\visha\PycharmProjects\GUI_Automation> pytest --html=Reports\report.html --self-contained-html --csv .\Logs\output.csv .\Tests\test_mpr3_creation.py --csv-columns id,module,file,markers,status,duration

**Comment by nicoulaj** [comment]
related: #8
